export const propertyTypes = [
    "Rent",
    "Sale"
]

export const cities = [
    "Deçan",
    "Dragash",
    "Ferizaj",
    "Fushë Kosovë",
    "Gjakovë",
    "Gjilan",
    "Graçanicë",
    "Gllogoc",
    "Hani i Elezit",
    "Istog",
    "Junik",
    "Kaçanik",
    "Kamenicë",
    "Klinë",
    "Kllokot",
    "Leposaviq",
    "Lipjan",
    "Malishevë",
    "Mamushë",
    "Mitrovicë e Jugut",
    "Mitrovicë e Veriut",
    "Novobërdë",
    "Obiliq",
    "Partesh",
    "Pejë",
    "Podujevë",
    "Prishtinë",
    "Prizren",
    "Rahovec",
    "Ranillug",
    "Skënderaj",
    "Shtime",
    "Shtërpcë",
    "Suharekë",
    "Viti",
    "Vushtrri",
    "Zubin Potok",
    "Zveçan"
];